/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';

import {
  EventEmitter,
} from '@stencil/core';

declare global {
  interface HTMLAppHomeElement extends HTMLStencilElement {

  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLGithubDashboardElement extends HTMLStencilElement {

  }
  var HTMLGithubDashboardElement: {
    prototype: HTMLGithubDashboardElement;
    new (): HTMLGithubDashboardElement;
  };
  interface HTMLElementTagNameMap {
    'github-dashboard': HTMLGithubDashboardElement;
  }
  interface ElementTagNameMap {
    'github-dashboard': HTMLGithubDashboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'github-dashboard': JSXElements.GithubDashboardAttributes;
    }
  }
  namespace JSXElements {
    export interface GithubDashboardAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLGithubRepoElement extends HTMLStencilElement {

  }
  var HTMLGithubRepoElement: {
    prototype: HTMLGithubRepoElement;
    new (): HTMLGithubRepoElement;
  };
  interface HTMLElementTagNameMap {
    'github-repo': HTMLGithubRepoElement;
  }
  interface ElementTagNameMap {
    'github-repo': HTMLGithubRepoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'github-repo': JSXElements.GithubRepoAttributes;
    }
  }
  namespace JSXElements {
    export interface GithubRepoAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLLazyImgElement extends HTMLStencilElement {
    'alt': string;
    'src': string;
    'width': number;
  }
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
      'width'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
